= Cloud Native Workshop

== Description

Please join Pivotal for a half-day hands-on workshop to introduce key concepts in modern cloud native application development and delivery. This half-day workshop will provide developers (and operators) with experience with Pivotal Cloud Foundry concepts, architecture, and the fundamentals of pushing code and building applications.

The session includes presentations, demos and a hands-on lab. It will cover general cloud native application trends and principles, an overview of Pivotal Cloud Foundry and relevant Spring projects, and how you can get involved as we go on this cloud native journey.

== Schedule
8:30 – 9:00 AM - Registration and Breakfast::

9:00 – 9:30 AM - Cloud Native Architectures and Frameworks::
 
  Overview of cloud native industry trends and practices including: 12 factor apps, microservices, and Spring Boot, and Spring Cloud

9:30 – 10:30 AM - Pivotal Cloud Foundry - The Cloud Native Platform::
 
  An overview of Pivotal Cloud Foundry and its Architecture

10:30 – 10:45 AM - Break::

10:45 – 11:00 AM - Demo: The developer and operator experiences::
  
  Pushing apps, the Cloud Foundry CLI, PCF Apps Manager, and PCF Ops Manager

11:00 – 11:50 AM - Hands-on Labs::

  Push, scale, bind, and monitor apps

11:50 AM - 12:00 PM - Wrap Up::

  Questions & Answers, Feedback

== Course Materials

* Session 1: link:presentations/Session_1_Cloud_Native_Enterprise.pptx[Welcome to the Cloud Native Enterprise]
* Session 2: link:presentations/Session_2_Architecture_And_Operations.pptx[Pivotal Cloud Foundry Architecture and Operations]
* Session 3: link:presentations/Session_3_Services_Overview.pptx[Pivotal Cloud Foundry Services]

* Developer Workshop
** Lab 1 - From Zero to Pushing Your First Application
*** link:labs/lab1/lab.adoc[**Java** Application]
*** link:labs/lab1/lab-ruby.adoc[**Ruby** Application]
*** link:labs/lab1/lab-node.adoc[**NodeJS** Application]
** link:labs/lab2/lab.adoc[Lab 2 - Binding to Cloud Foundry Services]
** link:labs/lab3/lab.adoc[Lab 3 - Operating Your Application]
** link:labs/lab4/lab.adoc[Lab 4 - Monitoring Your Application]
** link:labs/lab5/lab.adoc[Advanced Lab - Deploying a .NET Application]
** link:cf-spring-trader/README.md[Advanced Lab - Spring Cloud Services, _**Java** Only_]
** link:labs/lab5/continuous-delivery-lab.adoc[Advanced Lab - Jenkins Integration]

