= Cloud Native Workshop

== Description

Please join Pivotal for a half-day hands-on workshop to introduce key concepts in modern cloud native application development and delivery. This half-day workshop will provide developers (and operators) with experience with Pivotal Cloud Foundry concepts, architecture, and the fundamentals of pushing code and building applications.

The session includes presentations, demos and a hands-on lab. It will cover general cloud native application trends and principles, an overview of Pivotal Cloud Foundry and relevant Spring projects, and how you can get involved as we go on this cloud native journey.

Space is limited. Reserve your seat in the link:http://pivotal.io/event/cloud-native-workshop/st-louis[St. Louis workshop] today.

== Pre-requisites

* If you intend to participate in the hands-on lab, please bring your laptop.
* Pre-install the link:https://github.com/cloudfoundry/cli#downloads[Cloud Foundry CLI] in order to perform lab exercises.
* Create a link:http://run.pivotal.io/[Pivotal Cloud Foundry] trial account to run the lab and continue your own work after the workshop is complete.

== Getting started

Start by downloading the course materials. This can be accomplished either through the GitHub website or if you have Git installed, use the following commands:

```
$ git clone https://github.com/cbusch-pivotal/Cloud-Native-Workshop
$ cd Cloud-Native-Workshop/
$ git fetch --all
```

== Schedule
8:30 – 9:00 AM - Registration and Breakfast::

9:00 – 9:30 AM - Cloud Native Architectures and Frameworks::
 
  Overview of cloud native industry trends and practices including: 12-factor apps, microservices, Spring Boot, and Spring Cloud

9:30 – 10:30 AM - Pivotal Cloud Foundry - The Cloud Native Platform::
 
  An overview of Pivotal Cloud Foundry and its Architecture

10:30 – 10:45 AM - Break::

10:45 – 11:00 AM - Demo: The developer and operator experiences::
  
  Pushing apps, the Cloud Foundry CLI, PCF Apps Manager, and PCF Ops Manager

11:00 – 11:50 AM - Hands-on Labs::

  Push, scale, bind, and monitor apps

11:50 AM - 12:00 PM - Wrap Up::

  Questions & Answers, Feedback

== Course Materials

=== Session slides
* link:presentations/Session_1-Cloud_Native_Architectures_and_Frameworks.pptx[Cloud Native Architectures and Frameworks]
* link:presentations/Session_2-Pivotal_Cloud_Foundry-The_Cloud_Native_Platform.pptx[Pivotal Cloud Foundry - The Cloud Native Platform]

=== Hands-on Labs
** link:labs/lab1/lab.adoc[Lab 1 - From Zero to Pushing Your First Java Application]
** link:labs/lab2/lab.adoc[Lab 2 - Binding to Cloud Foundry Services]
** link:labs/lab3/lab.adoc[Lab 3 - Operating Your Application]
** link:labs/lab4/lab.adoc[Lab 4 - Monitoring Your Application]
** __Additional labs__
*** link:labs/lab1/lab-ruby.adoc[Push a Ruby Application]
*** link:labs/lab1/lab-node.adoc[Push a NodeJS Application]
*** link:labs/lab5/lab.adoc[Advanced Lab - Deploying a .NET Application]
*** link:cf-spring-trader/README.md[Advanced Lab - Spring Cloud Services, _**Java** Only_]
*** link:labs/lab5/continuous-delivery-lab.adoc[Advanced Lab - Jenkins Integration]

== Speakers

=== St. Louis Workshop

* Chris Busch, Platform Architect, cbusch@pivotal.io
* Steve Womack, Platform Architect, swomack@pivotal.io

