= Cloud Native Workshop

== Description

Join Pivotal technologists for this half-day workshop where you will discover how you can accelerate software development on a modern cloud platform without compromising operations.

In this workshop you will learn about developing and deploying cloud-native applications using production-ready industry best practices. You will also get hands-on experience as you use Pivotal’s Cloud Foundry platform to quickly deploy microservice applications developed using Spring Boot.

At the conclusion of this workshop, attendees take will have the knowledge and experience necessary to start the journey towards delivering cloud-native applications with the Pivotal Cloud Foundry platform.

== Schedule
8:30 – 9:00 AM::
 * _Registration and Breakfast_
9:00 – 9:30 AM::
 * _Cloud Native Architectures and Frameworks_ - Overview of cloud native industry trends and practices including: 12 factor apps, microservices, and Spring Boot, and Spring Cloud
9:30 – 10:30 AM::
 * _Pivotal Cloud Foundry - The Cloud Native Platform_ - An overview of Pivotal Cloud Foundry and its Architecture
10:30 – 10:45 AM::
 * _Break_
10:45 – 11:00 AM::
 * _Demo: The developer and operator experiences_ - Pushing apps, the Cloud Foundry CLI, PCF Apps Manager, and PCF Ops Manager
11:00 – 11:50 AM::
 * _Hands-on Labs_ (push, scale, bind, monitor)
11:50 AM - 12:00 PM::
 * _Wrap Up, Q&A, Feedback_

== Course Materials

* Session 1: link:presentations/Session_1_Cloud_Native_Enterprise.pptx[Welcome to the Cloud Native Enterprise]
* Session 2: link:presentations/Session_2_Architecture_And_Operations.pptx[Pivotal Cloud Foundry Architecture and Operations]
* Session 3: link:presentations/Session_3_Services_Overview.pptx[Pivotal Cloud Foundry Services]

* Developer Workshop
** Lab 1 - From Zero to Pushing Your First Application
*** link:labs/lab1/lab.adoc[**Java** Application]
*** link:labs/lab1/lab-ruby.adoc[**Ruby** Application]
*** link:labs/lab1/lab-node.adoc[**NodeJS** Application]
** link:labs/lab2/lab.adoc[Lab 2 - Binding to Cloud Foundry Services]
** link:labs/lab3/lab.adoc[Lab 3 - Operating Your Application]
** link:labs/lab4/lab.adoc[Lab 4 - Monitoring Your Application]
** link:labs/lab5/lab.adoc[Advanced Lab - Deploying a .NET Application]
** link:cf-spring-trader/README.md[Advanced Lab - Spring Cloud Services, _**Java** Only_]
** link:labs/lab5/continuous-delivery-lab.adoc[Advanced Lab - Jenkins Integration]

